# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [3]:
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
l1 = []
l2 = []
i = 5
j = 5
while i > 0:
    val1 = int(input("List 1: "))
    l1.append(val1)
    i -= 1
while j > 0:
    val2 = int(input("List 2: "))
    l2.append(val2)
    j -= 1
arr1 = np.array(l1)
arr2 = np.array(l2)
arr = np.concatenate((arr1,arr2))
print(np.sort(arr))

List 1: 1
List 1: 4
List 1: 6
List 1: 8
List 1: 9
List 2: 3
List 2: 2
List 2: 5
List 2: 9
List 2: 7
[1 2 3 4 5 6 7 8 9 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [10]:
import numpy as np
arr1 = np.array([1,4,6,8])
arr2 = np.arange(6).reshape(2,3)
arr3 = np.arange(10).reshape(5,2)
dim1 = arr1.ndim
dim2 = arr2.ndim
dim3 = arr3.ndim
print("Dimensions of these arrays are ",dim1,dim2,dim3)
print("The size of these arrays are ",arr1.size,arr2.size,arr3.size)

Dimensions of these arrays are  1 2 2
The size of these arrays are  4 6 10


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [31]:
arr = np.array([1,3,5])
arr = np.expand_dims(arr,axis = 0)
print(arr.shape)

arr1 = np.array([1,3,5,7]) 
print(arr1[np.newaxis,:].shape)

(1, 3)
(1, 4)


In [9]:
import numpy as np
arr = np.arange(4).reshape(2,2)
arr1 = np.arange(4).reshape(2,2)
print('Horizontal Append:',np.hstack((arr,arr1)))
print('Vertical Append:',np.vstack((arr,arr1)))

Horizontal Append: [[0 1 0 1]
 [2 3 2 3]]
Vertical Append: [[0 1]
 [2 3]
 [0 1]
 [2 3]]


# Questions 6:
How to get unique items and counts of unique items?

In [11]:
import numpy as np
arr = np.array([1,3,1,3,5,7,5,7,7,9])
unique,counts = np.unique(arr,return_counts = True)

print(np.asarray((unique,counts)).T)

[[1 2]
 [3 2]
 [5 2]
 [7 3]
 [9 1]]
